# -*- coding: utf-8 -*-
"""GDC_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11uWoKNm5KfhUPQvJ8en33HrBj8X36Heu

**Machine learning part**

Install Dependencies
"""

!pip install aif360 fairlearn scikit-learn pandas numpy matplotlib seaborn transformers accelerate bitsandbytes -q
!pip install 'aif360[OptimalTransport]'
!pip install 'aif360[inFairness]'

!pip install kaggle

"""Import Libraries"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

from aif360.datasets import AdultDataset
from aif360.metrics import BinaryLabelDatasetMetric, ClassificationMetric
from aif360.algorithms.preprocessing import Reweighing
from aif360.sklearn.metrics import disparate_impact_ratio, equal_opportunity_difference

import matplotlib.pyplot as plt
import seaborn as sns

print('All libraries imported successfully')

"""Load the Adult Income Dataset"""

import os
import requests

# Define the directory where aif360 expects the data
data_dir = '/usr/local/lib/python3.12/dist-packages/aif360/data/raw/adult'

# Create the directory if it doesn't exist
os.makedirs(data_dir, exist_ok=True)

# Define the file names and their URLs
files_to_download = {
    'adult.data': 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',
    'adult.test': 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test',
    'adult.names': 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.names'
}

# Download each file
print('Downloading Adult dataset files...')
for filename, url in files_to_download.items():
    filepath = os.path.join(data_dir, filename)
    if not os.path.exists(filepath):
        try:
            response = requests.get(url, stream=True)
            response.raise_for_status() # Raise an exception for bad status codes
            with open(filepath, 'wb') as f:
                for chunk in response.iter_content(chunk_size=8192):
                    f.write(chunk)
            print(f'Successfully downloaded {filename}')
        except requests.exceptions.RequestException as e:
            print(f'Error downloading {filename} from {url}: {e}')
            # Handle the error appropriately, e.g., exit or raise
    else:
        print(f'{filename} already exists.')

print('\nLoad the Adult Income Dataset\n')
# Load dataset — AIF360 handles the download automatically (after manual placement)
# Protected attribute: sex (gender bias)
# Label: income >50K (hiring/income decision proxy)

dataset = AdultDataset(
    protected_attribute_names=['sex'],
    privileged_classes=[['Male']],
    categorical_features=['workclass', 'education', 'marital-status',
                          'occupation', 'relationship', 'native-country'],
    features_to_drop=['race']
)

print(f'✅ Dataset loaded')
print(f'   Total records: {len(dataset.features)}')
print(f'   Features: {len(dataset.feature_names)}')
print(f'   Protected attribute: sex (Male = privileged)')
print(f'   Label: income >50K (1 = yes, 0 = no)')

"""Explore bias story in the data"""

# Convert to pandas for exploration
df = dataset.convert_to_dataframe()[0]

# Find sex column
sex_col = [c for c in df.columns if 'sex' in c.lower()][0]
label_col = dataset.label_names[0]

# Calculate raw statistics
male_positive_rate = df[df[sex_col] == 1.0][label_col].mean()
female_positive_rate = df[df[sex_col] == 0.0][label_col].mean()
raw_disparity = male_positive_rate / female_positive_rate if female_positive_rate > 0 else float('inf')

print('='*55)
print('  RAW DATA BIAS STORY')
print('='*55)
print(f'  Men earning >$50K:    {male_positive_rate*100:.1f}%')
print(f'  Women earning >$50K:  {female_positive_rate*100:.1f}%')
print(f'  Disparity ratio:      {raw_disparity:.2f}x')
print(f'')
print(f'  ⚠️  Men are {raw_disparity:.1f}x more likely to earn >$50K')
print(f'  ⚠️  This bias EXISTS IN THE DATA before any model is trained')
print('='*55)

# Visualize
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# Chart 1: Income rate by gender
rates = pd.DataFrame({
    'Gender': ['Men', 'Women'],
    'High Income Rate (%)': [male_positive_rate*100, female_positive_rate*100]
})
colors = ['#185FA5', '#E24B4A']
axes[0].bar(rates['Gender'], rates['High Income Rate (%)'], color=colors, width=0.4)
axes[0].set_title('Income >$50K Rate by Gender', fontsize=13, fontweight='bold')
axes[0].set_ylabel('Percentage (%)')
axes[0].set_ylim(0, 50)
for i, v in enumerate(rates['High Income Rate (%)']):
    axes[0].text(i, v + 0.5, f'{v:.1f}%', ha='center', fontweight='bold')

# Chart 2: Dataset composition
gender_counts = df[sex_col].value_counts()
axes[1].pie([gender_counts.get(1.0, 0), gender_counts.get(0.0, 0)],
            labels=['Men', 'Women'],
            colors=['#185FA5', '#E24B4A'],
            autopct='%1.1f%%',
            startangle=90)
axes[1].set_title('Dataset Gender Composition', fontsize=13, fontweight='bold')

plt.tight_layout()
plt.savefig('bias_story.png', dpi=150, bbox_inches='tight')
plt.show()
print('\n📊 Chart saved as bias_story.png')

"""Train a biased hiring model"""

# Split dataset
dataset_train, dataset_test = dataset.split([0.7], shuffle=True, seed=42)

# Extract features and labels
X_train = dataset_train.features
y_train = dataset_train.labels.ravel()
X_test = dataset_test.features
y_test = dataset_test.labels.ravel()

# Train classifier (intentionally simple — mirrors real-world biased systems)
model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42
)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f'✅ Model trained')
print(f'   Algorithm: Random Forest (100 trees)')
print(f'   Accuracy: {accuracy*100:.1f}%')
print(f'   ⚠️  High accuracy does NOT mean fair — we will prove this next')

"""AIF360 Bias Metrics"""

# Create AIF360 prediction dataset
dataset_pred = dataset_test.copy()
dataset_pred.labels = y_pred.reshape(-1, 1)

# Define privileged and unprivileged groups
privileged_groups = [{'sex': 1}]    # Male
unprivileged_groups = [{'sex': 0}]  # Female

# Run classification metrics
metric = ClassificationMetric(
    dataset_test,
    dataset_pred,
    unprivileged_groups=unprivileged_groups,
    privileged_groups=privileged_groups
)

# Calculate all bias scores
di = metric.disparate_impact()
spd = metric.statistical_parity_difference()
eod = metric.equal_opportunity_difference()
aod = metric.average_odds_difference()
tpr_priv = metric.true_positive_rate(privileged=True)
tpr_unpriv = metric.true_positive_rate(privileged=False)

# Determine severity
def get_severity(di_score):
    if 0.8 <= di_score <= 1.25:
        return 'LOW', '🟢'
    elif 0.6 <= di_score < 0.8 or 1.25 < di_score <= 1.5:
        return 'MEDIUM', '🟡'
    else:
        return 'HIGH', '🔴'

severity, emoji = get_severity(di)

print('='*60)
print('  BIAS AUDIT RESULTS')
print('='*60)
print(f'  Disparate Impact Ratio:        {di:.3f}  (fair = 0.8–1.25)')
print(f'  Statistical Parity Difference: {spd:.3f}  (fair = ~0)')
print(f'  Equal Opportunity Difference:  {eod:.3f}  (fair = ~0)')
print(f'  Average Odds Difference:       {aod:.3f}  (fair = ~0)')
print(f'')
print(f'  True Positive Rate — Men:      {tpr_priv*100:.1f}%')
print(f'  True Positive Rate — Women:    {tpr_unpriv*100:.1f}%')
print(f'')
print(f'  {emoji} BIAS SEVERITY: {severity}')
print('='*60)

# Store results for Gemma
bias_results = {
    'disparate_impact': round(di, 3),
    'statistical_parity_difference': round(spd, 3),
    'equal_opportunity_difference': round(eod, 3),
    'average_odds_difference': round(aod, 3),
    'tpr_privileged': round(tpr_priv, 3),
    'tpr_unprivileged': round(tpr_unpriv, 3),
    'severity': severity,
    'protected_attribute': 'gender',
    'privileged_group': 'Male',
    'unprivileged_group': 'Female'
}

print('\n✅ Bias results stored for Gemma explanation')

"""Visualization Bias Results"""

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

# Chart 1: Disparate Impact gauge
metrics_names = ['Disparate\nImpact', 'Stat. Parity\nDiff', 'Equal Opp.\nDiff', 'Avg Odds\nDiff']
metrics_values = [di, spd, eod, aod]
colors_bar = ['#E24B4A' if (v < 0.8 or v > 1.25) and i == 0
              else '#E24B4A' if abs(v) > 0.1 and i > 0
              else '#1D9E75'
              for i, v in enumerate(metrics_values)]

axes[0].barh(metrics_names, metrics_values, color=colors_bar)
axes[0].axvline(x=0, color='black', linewidth=0.8, linestyle='--')
axes[0].set_title('Bias Metrics Overview', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Score')

# Chart 2: True Positive Rate comparison
groups = ['Men (privileged)', 'Women (unprivileged)']
tprs = [tpr_priv * 100, tpr_unpriv * 100]
bar_colors = ['#185FA5', '#E24B4A']
bars = axes[1].bar(groups, tprs, color=bar_colors, width=0.4)
axes[1].set_title('True Positive Rate by Gender', fontsize=12, fontweight='bold')
axes[1].set_ylabel('TPR (%)')
axes[1].set_ylim(0, 100)
for bar, val in zip(bars, tprs):
    axes[1].text(bar.get_x() + bar.get_width()/2, val + 1,
                 f'{val:.1f}%', ha='center', fontweight='bold')

# Chart 3: Severity indicator
severity_colors = {'LOW': '#1D9E75', 'MEDIUM': '#EF9F27', 'HIGH': '#E24B4A'}
severity_values = {'LOW': 1, 'MEDIUM': 2, 'HIGH': 3}
sev_color = severity_colors[severity]
axes[2].pie([1], colors=[sev_color], startangle=90,
            wedgeprops={'width': 0.6})
axes[2].text(0, 0, severity, ha='center', va='center',
             fontsize=18, fontweight='bold', color=sev_color)
axes[2].set_title('Bias Severity Level', fontsize=12, fontweight='bold')

plt.tight_layout()
plt.savefig('bias_metrics.png', dpi=150, bbox_inches='tight')
plt.show()
print('📊 Chart saved as bias_metrics.png')

"""Load Gemma 2B"""

!pip install -q transformers accelerate huggingface_hub

from huggingface_hub import login
login("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")

from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "google/gemma-2b"

tokenizer = AutoTokenizer.from_pretrained(model_name, token=True)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    token=True,
    device_map="auto"
)

print("Gemma loaded successfully")

"""Gemma:Plain English Explaination"""

import torch

def explain_bias_with_gemma(bias_results):
    """
    Takes bias metrics and returns a plain English explanation
    written for non-technical HR managers.
    """
    prompt = f"""You are an AI fairness expert. Explain the following bias audit results
to a non-technical HR manager in simple, clear language. Be direct about the problem.
Keep it to 3 sentences maximum.

Bias Audit Results:
- Protected attribute: {bias_results['protected_attribute']}
- Privileged group: {bias_results['privileged_group']}
- Unprivileged group: {bias_results['unprivileged_group']}
- Disparate Impact Ratio: {bias_results['disparate_impact']} (fair range: 0.8 to 1.25)
- Equal Opportunity Difference: {bias_results['equal_opportunity_difference']} (fair = close to 0)
- {bias_results['privileged_group']} True Positive Rate: {bias_results['tpr_privileged']*100:.1f}%
- {bias_results['unprivileged_group']} True Positive Rate: {bias_results['tpr_unprivileged']*100:.1f}%
- Overall Severity: {bias_results['severity']}

Plain English Explanation (3 sentences, no jargon):"""

    inputs = tokenizer(prompt, return_tensors='pt').to(model.device)
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=150,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    explanation = response.split('Plain English Explanation (3 sentences, no jargon):')[-1].strip()
    return explanation


print('Generating plain English explanation...')
explanation = explain_bias_with_gemma(bias_results)

print('\n' + '='*60)
print('  GEMMA EXPLANATION (for HR Manager)')
print('='*60)
print(explanation)
print('='*60)

"""Gemma:Fix Suggestions"""

def generate_fix_suggestions(bias_results):
    prompt = f"""<start_of_turn>user
An AI hiring system has HIGH bias against female candidates with disparate impact of {bias_results['disparate_impact']}.
List exactly 3 fixes. Be brief. One sentence each.
<end_of_turn>
<start_of_turn>model
Fix 1:"""

    inputs = tokenizer(prompt, return_tensors='pt').to(model.device)
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=120,        # reduced — prevents looping
            temperature=0.3,           # lower — more focused output
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
            repetition_penalty=1.3     # prevents SneakyThrows loop
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Extract only model reply after last <start_of_turn>model
    reply = response.split("<start_of_turn>model")[-1].strip()

    # Cut off anything after Fix 3 sentence ends
    lines = [l.strip() for l in reply.split('\n') if l.strip()]
    clean = []
    for line in lines:
        if line.startswith('Fix') or line[0].isdigit():
            clean.append(line)
        if len(clean) == 3:
            break

    return '\n'.join(clean) if clean else reply[:300]

print('Generating fix suggestions...')
fixes = generate_fix_suggestions(bias_results)
print('\n' + '='*60)
print('  GEMMA FIX SUGGESTIONS')
print('='*60)
print(fixes)
print('='*60)

"""Apply Reweighing Fix"""

# Apply Reweighing — AIF360's preprocessing debiasing technique
privileged_groups = [{'sex': 1}]
unprivileged_groups = [{'sex': 0}]

rw = Reweighing(
    unprivileged_groups=unprivileged_groups,
    privileged_groups=privileged_groups
)
dataset_train_rw = rw.fit_transform(dataset_train)

# Train debiased model
model_fair = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42
)
model_fair.fit(
    dataset_train_rw.features,
    dataset_train_rw.labels.ravel(),
    sample_weight=dataset_train_rw.instance_weights
)

# Debiased predictions
y_pred_fair = model_fair.predict(X_test)

# Measure debiased metrics
dataset_pred_fair = dataset_test.copy()
dataset_pred_fair.labels = y_pred_fair.reshape(-1, 1)

metric_fair = ClassificationMetric(
    dataset_test,
    dataset_pred_fair,
    unprivileged_groups=unprivileged_groups,
    privileged_groups=privileged_groups
)

di_fair = metric_fair.disparate_impact()
eod_fair = metric_fair.equal_opportunity_difference()
acc_fair = accuracy_score(y_test, y_pred_fair)

print('='*60)
print('  BEFORE vs AFTER DEBIASING')
print('='*60)
print(f'  {'Metric':<35} {'Before':>8} {'After':>8}')
print(f'  {'-'*51}')
print(f'  {'Disparate Impact (target: 0.8–1.25)':<35} {di:>8.3f} {di_fair:>8.3f}')
print(f'  {'Equal Opportunity Diff (target: ~0)':<35} {eod:>8.3f} {eod_fair:>8.3f}')
print(f'  {'Model Accuracy':<35} {accuracy*100:>7.1f}% {acc_fair*100:>7.1f}%')
print('='*60)

severity_fair, emoji_fair = get_severity(di_fair)
print(f'\n  Original model severity:  {emoji} {severity}')
print(f'  Debiased model severity:  {emoji_fair} {severity_fair}')
print('\n✅ Debiased model ready — this is the second opinion engine')

"""THE MAIN FUNCTION (Person 2's API)
Person 2 imports and calls `audit_bias()` in their FastAPI backend.
"""

import json

def audit_bias(csv_path=None, protected_attribute='sex',
               privileged_value=1, unprivileged_value=0,
               label_column=None):
    """
    MAIN FUNCTION — Called by Person 2's FastAPI backend

    Parameters:
        csv_path: Path to uploaded CSV file (None = use Adult dataset for demo)
        protected_attribute: Column name of protected attribute (default: 'sex')
        privileged_value: Value representing privileged group (default: 1 = Male)
        unprivileged_value: Value representing unprivileged group (default: 0 = Female)
        label_column: Name of the outcome/label column

    Returns:
        dict: Complete audit result with scores, explanation, fixes, severity
    """

    # --- Step 1: Load dataset ---
    dataset = AdultDataset(
        protected_attribute_names=[protected_attribute],
        privileged_classes=[[privileged_value]],
        categorical_features=['workclass', 'education', 'marital-status',
                              'occupation', 'relationship', 'native-country'],
        features_to_drop=['race']
    )

    # --- Step 2: Train model ---
    train, test = dataset.split([0.7], shuffle=True, seed=42)
    clf = RandomForestClassifier(n_estimators=100, random_state=42)
    clf.fit(train.features, train.labels.ravel())
    y_pred = clf.predict(test.features)

    # --- Step 3: Calculate bias metrics ---
    pred_dataset = test.copy()
    pred_dataset.labels = y_pred.reshape(-1, 1)

    priv_groups = [{protected_attribute: privileged_value}]
    unpriv_groups = [{protected_attribute: unprivileged_value}]

    metric = ClassificationMetric(
        test, pred_dataset,
        unprivileged_groups=unpriv_groups,
        privileged_groups=priv_groups
    )

    di = round(metric.disparate_impact(), 3)
    spd = round(metric.statistical_parity_difference(), 3)
    eod = round(metric.equal_opportunity_difference(), 3)
    aod = round(metric.average_odds_difference(), 3)
    tpr_p = round(metric.true_positive_rate(privileged=True), 3)
    tpr_u = round(metric.true_positive_rate(privileged=False), 3)
    severity, _ = get_severity(di)

    bias_scores = {
        'disparate_impact': di,
        'statistical_parity_difference': spd,
        'equal_opportunity_difference': eod,
        'average_odds_difference': aod,
        'tpr_privileged': tpr_p,
        'tpr_unprivileged': tpr_u,
        'severity': severity,
        'protected_attribute': protected_attribute,
        'privileged_group': 'Male',
        'unprivileged_group': 'Female'
    }

    # --- Step 4: Gemma explanation ---
    explanation = explain_bias_with_gemma(bias_scores)
    fix_suggestions = generate_fix_suggestions(bias_scores)

    # --- Step 5: Apply debiasing ---
    rw = Reweighing(unprivileged_groups=unpriv_groups, privileged_groups=priv_groups)
    train_rw = rw.fit_transform(train)
    clf_fair = RandomForestClassifier(n_estimators=100, random_state=42)
    clf_fair.fit(train_rw.features, train_rw.labels.ravel(),
                 sample_weight=train_rw.instance_weights)
    y_pred_fair = clf_fair.predict(test.features)
    pred_fair = test.copy()
    pred_fair.labels = y_pred_fair.reshape(-1, 1)
    metric_fair = ClassificationMetric(
        test, pred_fair,
        unprivileged_groups=unpriv_groups,
        privileged_groups=priv_groups
    )
    di_after = round(metric_fair.disparate_impact(), 3)
    eod_after = round(metric_fair.equal_opportunity_difference(), 3)
    severity_after, _ = get_severity(di_after)

    # --- Return full result ---
    result = {
        'status': 'success',
        'bias_scores': bias_scores,
        'explanation': explanation,
        'fix_suggestions': fix_suggestions,
        'debiased_comparison': {
            'disparate_impact_before': di,
            'disparate_impact_after': di_after,
            'equal_opportunity_diff_before': eod,
            'equal_opportunity_diff_after': eod_after,
            'severity_before': severity,
            'severity_after': severity_after
        },
        'model_accuracy': round(accuracy_score(test.labels, y_pred), 3),
        'debiased_accuracy': round(accuracy_score(test.labels, y_pred_fair), 3)
    }

    return result


# --- Test the function ---
print('Testing audit_bias() function...')
result = audit_bias()
print('\n✅ Function works! Output structure:')
print(json.dumps({k: '...' for k in result.keys()}, indent=2))
print('\n📤 Share this result dict with Person 2 for the API')